# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TODO:
# 1- Update Glance images with: shorter names plus description

- name: Adding a few Operating System images into Glance
  environment: admin_openrc_env
  command: "{{item}}"
  with_items:
  - glance image-create --location http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1503.qcow2c --name "CentOS 7 - 64-bit - Cloud Based Image" --is-public true --container-format bare --disk-format qcow2
  - glance image-create --location http://cloud.centos.org/centos/6.6/images/CentOS-6-x86_64-GenericCloud-20141129_01.qcow2c --name "CentOS 6.6 - 64-bit - Cloud Based Image" --is-public true --container-format bare --disk-format qcow2
  - glance image-create --location http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-i386-disk.img --name "CirrOS 0.3.4 - Minimalist - 32-bit - Cloud Based Image" --is-public true --container-format bare --disk-format qcow2
  - glance image-create --location http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img --name "CirrOS 0.3.4 - Minimalist - 64-bit - Cloud Based Image" --is-public true --container-format bare --disk-format qcow2
  - glance image-create --location http://uec-images.ubuntu.com/releases/15.04/release/ubuntu-15.04-server-cloudimg-i386-disk1.img --is-public true --disk-format qcow2 --container-format bare --name "Ubuntu 15.04 - Vivid Vervet - 32-bit - Cloud Based Image"
  - glance image-create --location http://uec-images.ubuntu.com/releases/15.04/release/ubuntu-15.04-server-cloudimg-amd64-disk1.img --is-public true --disk-format qcow2 --container-format bare --name "Ubuntu 15.04 - Vivid Vervet - 64-bit - Cloud Based Image"
  - glance image-create --location http://uec-images.ubuntu.com/releases/12.04.4/12.04.5/ubuntu-12.04-server-cloudimg-i386-disk1.img --is-public true --disk-format qcow2 --container-format bare --name "Ubuntu 12.04.5 LTS - Precise Pangolin - 32-bit - Cloud Based Image"
  - glance image-create --location http://uec-images.ubuntu.com/releases/12.04.4/12.04.5/ubuntu-12.04-server-cloudimg-amd64-disk1.img --is-public true --disk-format qcow2 --container-format bare --name "Ubuntu 12.04.5 LTS - Precise Pangolin - 64-bit - Cloud Based Image"
  - glance image-create --location http://uec-images.ubuntu.com/releases/14.04.3/release/ubuntu-14.04-server-cloudimg-i386-disk1.img --is-public true --disk-format qcow2 --container-format bare --name "Ubuntu 14.04.3 LTS - Trusty Tahr - 32-bit - Cloud Based Image"
  - glance image-create --location http://uec-images.ubuntu.com/releases/14.04.3/release/ubuntu-14.04-server-cloudimg-amd64-disk1.img --is-public true --disk-format qcow2 --container-format bare --name "Ubuntu 14.04.3 LTS - Trusty Tahr - 64-bit - Cloud Based Image"
  - glance image-create --location http://cdimage.debian.org/cdimage/openstack/8.4.0/debian-8.4.0-openstack-amd64.qcow2 --is-public true --disk-format qcow2 --container-format bare --name "Debian 8.4.0 - Jessie - 64-bit - Cloud Based Image"
  - glance image-update --property hw_scsi_model=virtio-scsi --property hw_disk_bus=scsi "CentOS 7 - 64-bit - Cloud Based Image"
  - glance image-update --property hw_scsi_model=virtio-scsi --property hw_disk_bus=scsi "CentOS 6.6 - 64-bit - Cloud Based Image"
  - glance image-update --property hw_scsi_model=virtio-scsi --property hw_disk_bus=scsi "CirrOS 0.3.4 - Minimalist - 32-bit - Cloud Based Image"
  - glance image-update --property hw_scsi_model=virtio-scsi --property hw_disk_bus=scsi "CirrOS 0.3.4 - Minimalist - 64-bit - Cloud Based Image"
  - glance image-update --property hw_scsi_model=virtio-scsi --property hw_disk_bus=scsi "Ubuntu 15.04 - Vivid Vervet - 32-bit - Cloud Based Image"
  - glance image-update --property hw_scsi_model=virtio-scsi --property hw_disk_bus=scsi "Ubuntu 15.04 - Vivid Vervet - 64-bit - Cloud Based Image"
  - glance image-update --property hw_scsi_model=virtio-scsi --property hw_disk_bus=scsi "Ubuntu 12.04.5 LTS - Precise Pangolin - 32-bit - Cloud Based Image"
  - glance image-update --property hw_scsi_model=virtio-scsi --property hw_disk_bus=scsi "Ubuntu 12.04.5 LTS - Precise Pangolin - 64-bit - Cloud Based Image"
  - glance image-update --property hw_scsi_model=virtio-scsi --property hw_disk_bus=scsi "Ubuntu 14.04.3 LTS - Trusty Tahr - 32-bit - Cloud Based Image"
  - glance image-update --property hw_scsi_model=virtio-scsi --property hw_disk_bus=scsi "Ubuntu 14.04.3 LTS - Trusty Tahr - 64-bit - Cloud Based Image"
  when: api_started|changed and registry_started|changed
  register: glance_images_created
