#! /bin/sh

version="$1"

# passing the kernel version is required
[ -z "${version}" ] && exit 0

dpkg-statoverride --remove /boot/vmlinuz-${version}

dpkg-statoverride --update --add root root 0644 /boot/vmlinuz-${version}
